services:
  - type: web
    name: skypoint-social-backend
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=skypoint.db
      - key: Jwt__Key
        value: MySuperSecretKeyForJwtToken123!@#2024
      - key: Jwt__Issuer
        value: SkypointPlatform
      - key: Jwt__Audience
        value: SkypointUsers
