services:
  - type: web
    name: skypoint-social-backend
    env: docker # <–– Trick: this forces it to use a custom setup
    plan: free
    buildCommand: dotnet build Skypoint.API/Skypoint.API/Skypoint.API.csproj
    startCommand: dotnet Skypoint.API/Skypoint.API/Skypoint.API.dll
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=skypoint.db
      - key: Jwt__Key
        value: MySuperSecretKeyForJwtToken123!@#2024
      - key: Jwt__Issuer
        value: SkypointPlatform
      - key: Jwt__Audience
        value: SkypointUsers
